version: '3'
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_DEVACTIVITYPANEL: FALSE  # optimización propuesta por https://rlodeiro.info/blog/navidrome/
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data

volumes:
  data:
  music:
