version: '3'
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    dns:
      - 9.9.9.9
      - 1.1.1.1
    restart: unless-stopped
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_DEVACTIVITYPANEL: "false"  # optimización propuesta por https://rlodeiro.info/blog/navidrome/
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
  asknavidrome:
    image: ghcr.io/rosskouk/asknavidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - 5000:5000
    dns:
      - 9.9.9.9
      - 1.1.1.1
    restart: unless-stopped
    environment:

      NAVI_SONG_COUNT: 50
      NAVI_PORT: 443
      NAVI_API_PATH: /rest
      NAVI_API_VER: 1.16.1
      NAVI_DEBUG: 0
volumes:
  data:
  music:
